name: nightly build
on:
  schedule:
    - cron: "0 22 * * *"  # The start of builld is 7:00 AM JST. We wish to end until 10:00 AM JST.
  workflow_dispatch:


jobs:
  build-focal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          packer_definition_path: images/linux/ubuntu2004.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          notify: true
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          retention-days: 5
  build-jammy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          packer_definition_path: images/linux/ubuntu2204.pkr.hcl
          github_token: ${{ secrets.GITHUB_TOKEN }}
          notify: true
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          retention-days: 5
